-- Parking Reservation MVP
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  spot_number integer not null check (
    spot_number between 3028 and 3039
    or spot_number between 3113 and 3118
    or spot_number between 3183 and 3199
  ),
  reservation_date date not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (spot_number, reservation_date)
);

create index if not exists reservations_date_idx
  on public.reservations(reservation_date);

-- Keep the database in sync with the actual parking spots.
alter table public.reservations drop constraint if exists reservations_spot_number_check;
alter table public.reservations add constraint reservations_spot_number_check check (
  spot_number between 3028 and 3039
  or spot_number between 3113 and 3118
  or spot_number between 3183 and 3199
);

alter table public.profiles enable row level security;
alter table public.reservations enable row level security;

-- Helper function to avoid recursive profile policies.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin"
on public.profiles for update
to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

drop policy if exists "reservations_select_authenticated" on public.reservations;
create policy "reservations_select_authenticated"
on public.reservations for select
to authenticated
using (true);

drop policy if exists "reservations_insert_own" on public.reservations;
create policy "reservations_insert_own"
on public.reservations for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "reservations_delete_own_or_admin" on public.reservations;
create policy "reservations_delete_own_or_admin"
on public.reservations for delete
to authenticated
using (user_id = auth.uid() or public.is_admin());

-- Automatically create a profile when a user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Enable realtime for reservation changes.
do $$
begin
  alter publication supabase_realtime add table public.reservations;
exception
  when duplicate_object then null;
end $$;